# Generated by Django 3.2.12 on 2022-04-02 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20220402_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='photo',
            new_name='image',
        ),
    ]
