# Generated by Django 3.2.12 on 2022-04-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_rename_photo_student_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mname',
            new_name='middlename',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='roll_no',
            new_name='rollno',
        ),
    ]
